paths:
  /alram/{place}:
    get:
      tags:
        - Alram
      summary: 알람 종류별로 불러오기
      security:
        - Authorization: []
      parameters:
      - name: place
        in: path
        required: true
        description: home, checklist, family, postbox로 구분해뒀습니다!
        type: string
        example: "family"

      responses:
        '200':
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              count:
                type: integer
                example: 3
        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
        '401':
          description: 토큰 오류
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 401
              isSuccess:  
                type: boolean
                example: false
              error:
                type: string
                example: 유효하지 않은 토큰입니다.
        '4001':
          description: 파라미터 오류
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 4001
              isSuccess:
                type: boolean
                example: false
              message:
                type: string
                example: 쿼리 실행 시 전달되는 파라미터가 잘못되었습니다. 파라미터 개수 혹은 파라미터 형식을 확인해주세요.
      
