paths:
  /check/add:
    post:
      tags:
        - Checklist
      summary: 체크리스트 추가
      security:
        - Authorization: []
      parameters:
        - name: add
          in: body
          required: true
          schema:
            properties:
              receiver_idx:
                type: string
                description: 체크리스트 추가 대상
                example: "3304133093"
              due_year:
                type: integer
                description: 생일 년도
                example: 2000
              due_month:
                type: integer
                description: 생일 월(한자리 숫자면 05 안되고 5로 적어주세요!)
                example: 12
              due_day:
                type: integer
                description: 생일 일(한자리 숫자면 05 안되고 5로 적어주세요!)
                example: 5
              content:
                type: string
                description: 체크리스트 내용
                example: 화이팅 힘내서 열심히 할 일 하기
      
      responses:
        '200':
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              check:
                type: json
                example: {
                  checkid: 3,
                  due_date: '2024-02-13',
                  complete: 0,
                  picture: null,
                  content: "열심히 살기",
                  create_at : '2024-02-13 22:22:22',
                  modify_at : null,
                  sender: "임세현",
                  receiver: "김정훈"              
                }
        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
        '401':
          description: 토큰 오류
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 401
              isSuccess:  
                type: boolean
                example: false
              error:
                type: string
                example: 유효하지 않은 토큰입니다.
        '4001':
          description: 파라미터 오류
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 4001
              isSuccess:
                type: boolean
                example: false
              message:
                type: string
                example: 쿼리 실행 시 전달되는 파라미터가 잘못되었습니다. 파라미터 개수 혹은 파라미터 형식을 확인해주세요.


  /check/{userid}/{mode}/{date}:
    get:
      tags:
        - Checklist
      summary: 가족 구성원 1인 체크리스트 날짜별로 불러오기
      security:
        - Authorization: []
      parameters:
      - name: userid
        in: path
        required: true
        description: 불러올 체크리스트의 주인
        type: string
        example: "3304133093"
      - name: mode
        in: path
        required: true
        description: 본인 체크리스트 조회는 false, 다른 사람 체크리스트 조회는 true
        type: boolean
        example: 1
      - name: date
        in: path
        required: true
        description: 불러올 체크리스트의 날짜(YYYY-MM-DD)
        type: string
        example: 2022-01-01

      responses:
        '200':
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              checklist:
                type: json
                example: [
                  {
                    checkid: 3,
                    due_date: '2024-02-13',
                    complete: 0,
                    picture: null,
                    content: "열심히 살기",
                    create_at : '2024-02-13 22:22:22',
                    modify_at : null,
                    sender: "임세현",
                    receiver: "김정훈"              
                  },
                  {
                    checkid: 3,
                    due_date: '2024-02-13',
                    complete: 0,
                    picture: null,
                    content: "행복하게 살기",
                    create_at : '2024-02-13 22:22:23',
                    modify_at : null,
                    sender: "임세현",
                    receiver: "김정훈"              
                  }
                ]
        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
        '401':
          description: 토큰 오류
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 401
              isSuccess:  
                type: boolean
                example: false
              error:
                type: string
                example: 유효하지 않은 토큰입니다.
        '451':
          description: 체크리스트 없음
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 451
              isSuccess:
                type: boolean
                example: false
              message:
                type: string
                example: 해당 날짜에 만들어진 체크리스트가 없습니다
        '4001':
          description: 파라미터 오류
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 4001
              isSuccess:
                type: boolean
                example: false
              message:
                type: string
                example: 쿼리 실행 시 전달되는 파라미터가 잘못되었습니다. 파라미터 개수 혹은 파라미터 형식을 확인해주세요.
      

  /check/{checkid}/content:
    put:
      tags:
        - Checklist
      summary: 체크리스트 내용 수정
      security:
        - Authorization: []
      parameters:
      - name: checkid
        in: path
        required: true
        description: 수정할 체크리스트의 고유번호
        type: integer
        example: 13
      - name: content
        in: body
        required: true
        schema:
          properties:
            content:
              type: string
              description: 수정할 체크리스트 내용입니다 !
              example: "이렇게 바뀔거에요"
      
      responses:
        '200':
          description: 체크리스트 내용 변경 성공
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              check:
                type: json
                example: {
                  checkid: 3,
                  due_date: '2024-02-13',
                  complete: 0,
                  picture: null,
                  content: "열심히 살기",
                  create_at : '2024-02-13 22:22:22',
                  modify_at : '2024-02-13 22:44:44',
                  sender: "임세현",
                  receiver: "김정훈"              
                }
        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
        '401':
          description: 토큰 오류
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 401
              isSuccess:  
                type: boolean
                example: false
              error:
                type: string
                example: 유효하지 않은 토큰입니다.
        '4001':
          description: 파라미터 오류
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 4001
              isSuccess:
                type: boolean
                example: false
              message:
                type: string
                example: 쿼리 실행 시 전달되는 파라미터가 잘못되었습니다. 파라미터 개수 혹은 파라미터 형식을 확인해주세요.


  /check/{checkid}/date/{date}:
    put:
      tags:
        - Checklist
      summary: 체크리스트 기한 변경
      security:
        - Authorization: []
      parameters:
      - name: checkid
        in: path
        required: true
        description: 수정할 체크리스트의 고유번호
        type: integer
        example: 13
      - name: date
        in: path
        required: true
        description: 체크리스트가 변경될 날짜(YYYY-MM-DD)
        type: string
        example: 2024-02-15
      
      responses:
        '200':
          description: 체크리스트 기한 변경 성공
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              check:
                type: json
                example: {
                  checkid: 3,
                  due_date: '2024-02-15',
                  complete: 0,
                  picture: null,
                  content: "열심히 살기",
                  create_at : '2024-02-13 22:22:22',
                  modify_at : '2024-02-13 22:44:44',
                  sender: "임세현",
                  receiver: "김정훈"              
                }
        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
        '401':
          description: 토큰 오류
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 401
              isSuccess:  
                type: boolean
                example: false
              error:
                type: string
                example: 유효하지 않은 토큰입니다.
        '4001':
          description: 파라미터 오류
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 4001
              isSuccess:
                type: boolean
                example: false
              message:
                type: string
                example: 쿼리 실행 시 전달되는 파라미터가 잘못되었습니다. 파라미터 개수 혹은 파라미터 형식을 확인해주세요.


  /check/{checkid}/complete:
    put:
      tags:
        - Checklist
      summary: 체크리스트 완료 여부 변경
      security:
        - Authorization: []
      parameters:
      - name: checkid
        in: path
        required: true
        description: 수정할 체크리스트 고유번호
        type: integer
        example: 13

      responses:
        '200':
          description: 체크리스트 완료 여부 변경 성공
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              check:
                type: json
                example: {
                  checkid: 3,
                  due_date: '2024-02-15',
                  complete: 1,
                  picture: null,
                  content: "열심히 살기",
                  create_at : '2024-02-13 22:22:22',
                  modify_at : '2024-02-13 22:44:44',
                  sender: "임세현",
                  receiver: "김정훈"              
                }
        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
        '401':
          description: 토큰 오류
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 401
              isSuccess:  
                type: boolean
                example: false
              error:
                type: string
                example: 유효하지 않은 토큰입니다.
        '4001':
          description: 파라미터 오류
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 4001
              isSuccess:
                type: boolean
                example: false
              message:
                type: string
                example: 쿼리 실행 시 전달되는 파라미터가 잘못되었습니다. 파라미터 개수 혹은 파라미터 형식을 확인해주세요.
      

  /check/{checkid}:
    delete:
      tags:
        - Checklist
      summary:
      security:
        - Authorization: []
      parameters:
      - name: checkid
        in: path
        required: true
        description: 삭제할 체크리스트 고유번호
        type: integer
        example: 13
      
      responses:
        '200':
          description: 체크리스트 삭제 성공
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              message:
                type: json
                example: 체크리스트를 삭제했습니다
        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
        '401':
          description: 토큰 오류
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 401
              isSuccess:  
                type: boolean
                example: false
              error:
                type: string
                example: 유효하지 않은 토큰입니다.
        '4001':
          description: 파라미터 오류
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 4001
              isSuccess:
                type: boolean
                example: false
              message:
                type: string
                example: 쿼리 실행 시 전달되는 파라미터가 잘못되었습니다. 파라미터 개수 혹은 파라미터 형식을 확인해주세요.
    

  /check/img:
    patch:
      tags:
        - Checklist
      summary: 체크리스트 인증샷 추가
      security:
        - Authorization: []
      parameters:
        - name: image
          in: formData
          type: file
          required: true
          description: 체크리스트에 인증샷으로 첨부할 이미지
        - name: checkid
          in: formData
          type: integer
          required: true
          description: 인증샷을 추가할 체크리스트 인덱스 번호
      
      responses:
        '200':
          description: 인증샷 추가 성공
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              check:
                type: json
                example: {
                  checkid: 3,
                  due_date: '2024-02-15',
                  complete: 1,
                  picture: '사진 url',
                  content: "열심히 살기",
                  create_at : '2024-02-13 22:22:22',
                  modify_at : '2024-02-13 22:44:44',
                  sender: "임세현",
                  receiver: "김정훈"              
                }
        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
        '401':
          description: 토큰 오류
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 401
              isSuccess:  
                type: boolean
                example: false
              error:
                type: string
                example: 유효하지 않은 토큰입니다.
        '450':
          description: 미완료 체크리스트
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 450
              isSuccess: 
                type: boolean
                example: false
              error:
                type: string
                example: 체크리스트 달성 전에는 인증샷을 추가할 수 없습니다
        '4001':
          description: 파라미터 오류
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 4001
              isSuccess:
                type: boolean
                example: false
              message:
                type: string
                example: 쿼리 실행 시 전달되는 파라미터가 잘못되었습니다. 파라미터 개수 혹은 파라미터 형식을 확인해주세요.

