paths:
  /mail/all/{today}:
    get:
      tags:
        - Postbox
      summary: 전체 게시물 받아오기
      security:
        - Authorization: []
      parameters:
      - name: today
        in: path
        required: true
        description: 선택된 날짜
        type: string
        example: 2024-02-06
      responses:
        '200':
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              post:
                type: json
                example: [
                    {
                      "postbox_idx": 1,
                      "sender_idx": "한승민",
                      "voice": 0,
                      "content": "1234",
                      "question": "오늘의 기분은 어떠신가요?",
                      "is_read": 0,
                    },
                    {
                      "postbox_idx": 2,
                      "sender_idx": "한승민",
                      "voice": 0,
                      "is_read": 0,
                      "question": "오늘의 기분은 어떠신가요?"
                    }
                  ]
        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
        '401':
          description: 토큰 오류
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 401
              isSuccess:  
                type: boolean
                example: false
              error:
                type: string
                example: 유효하지 않은 토큰입니다.
             
        '4001':
          description: 파라미터 오류
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 4001
              isSuccess:
                type: boolean
                example: false
              message:
                type: string
                example: 쿼리 실행 시 전달되는 파라미터가 잘못되었습니다. 파라미터 개수 혹은 파라미터 형식을 확인해주세요.
  /mail/one/{idx}:
    get:
      tags:
        - Postbox
      summary: 편지 하나 받아오기
      security:
        - Authorization: []
      parameters:
      - name: idx
        in: path
        required: true
        type: integer
        example: 1
      responses:
        '200':
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              post:
                type: json
                example: [
                    {
                      "postbox_idx": 1,
                      "sender_idx": "한승민",
                      "receiver_idx": "한승민",
                      "content": "fdsfd",
                      "voice": 0,
                      "send_date": "2024-02-05T15:00:00.000Z",
                      "is_read": 0,
                      "question": "오늘의 기분은 어떠신가요?"
                    }
                  ]
        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
        '401':
          description: 토큰 오류
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 401
              isSuccess:  
                type: boolean
                example: false
              error:
                type: string
                example: 유효하지 않은 토큰입니다.
             
        '4001':
          description: 파라미터 오류
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 4001
              isSuccess:
                type: boolean
                example: false
              message:
                type: string
                example: 쿼리 실행 시 전달되는 파라미터가 잘못되었습니다. 파라미터 개수 혹은 파라미터 형식을 확인해주세요.
      
  /mail/voice:
    post:
      tags:
        - Postbox
      summary: 파일 및 다른 데이터 업로드
      consumes:
        - multipart/form-data
      security:
        - Authorization: []
      parameters:
        - name: member
          in: formData
          type: array
          items:
            type: integer
          example: [3303580750, 3304133093]
        - name: question
          in: formData
          type: string
          required: true
        - name: record
          in: formData
          type: file
          required: true
      responses:
        '200':
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              message:
                type: string
                example: 성공하셨습니다:)
        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
        '401':
          description: 토큰 오류
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 401
              isSuccess:  
                type: boolean
                example: false
              error:
                type: string
                example: 유효하지 않은 토큰입니다.
             
        '4001':
          description: 파라미터 오류
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 4001
              isSuccess:
                type: boolean
                example: false
              message:
                type: string
                example: 쿼리 실행 시 전달되는 파라미터가 잘못되었습니다. 파라미터 개수 혹은 파라미터 형식을 확인해주세요.
  
  /mail/text:
    post:
      tags:
        - Postbox
      summary: 텍스트 편지 업로드
      security:
        - Authorization: []
      parameters:
        - name: member
          in: formData
          type: array
          items:
            type: integer
          example: [3303580750, 3304133093]
        - name: question
          in: formData
          type: string
          required: true
        - name: content
          in: formData
          required: true
          type: string

      responses:
        '200':
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              message:
                type: string
                example: 성공하셨습니다:)
        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
        '401':
          description: 토큰 오류
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 401
              isSuccess:  
                type: boolean
                example: false
              error:
                type: string
                example: 유효하지 않은 토큰입니다.
             
        '4001':
          description: 파라미터 오류
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 4001
              isSuccess:
                type: boolean
                example: false
              message:
                type: string
                example: 쿼리 실행 시 전달되는 파라미터가 잘못되었습니다. 파라미터 개수 혹은 파라미터 형식을 확인해주세요.
      
  /mail/question:
    get:
      tags:
        - Postbox
      summary: 오늘의 질문 받아오기
      security:
        - Authorization: []
      
      responses:
        '200':
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              question:
                type: json
                example: [
                    {
                      "question": "오늘의 기분은 어떠신가요?"
                    }
                  ]
        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
        '401':
          description: 토큰 오류
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 401
              isSuccess:  
                type: boolean
                example: false
              error:
                type: string
                example: 유효하지 않은 토큰입니다.
        '405':
          description: 가족장 승인 미완료
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 405
              isSuccess:
                type: boolean
                example: false
              error:
                type: string
                example: "아직 가족이 없습니다! 가족장의 승인을 받아주세요"           
        '4001':
          description: 파라미터 오류
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 4001
              isSuccess:
                type: boolean
                example: false
              message:
                type: string
                example: 쿼리 실행 시 전달되는 파라미터가 잘못되었습니다. 파라미터 개수 혹은 파라미터 형식을 확인해주세요.