paths:
  /mail/voice:
    post:
      tags:
        - postbox
      summary: 파일 및 다른 데이터 업로드
      consumes:
        - multipart/form-data
      security:
        - Authorization: []
      parameters:
        - name: member
          in: formData
          type: array
          items:
            type: integer
          example: [3303580750, 3304133093]
        - name: record
          in: formData
          type: file
          required: true
      responses:
        '200':
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              message:
                type: string
                example: 1ee0cbce41a4c539
        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
        '401':
          description: 토큰 오류
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 401
              isSuccess:  
                type: boolean
                example: false
              error:
                type: string
                example: 유효하지 않은 토큰입니다.
             
        '4001':
          description: 파라미터 오류
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 4001
              isSuccess:
                type: boolean
                example: false
              message:
                type: string
                example: 쿼리 실행 시 전달되는 파라미터가 잘못되었습니다. 파라미터 개수 혹은 파라미터 형식을 확인해주세요.
  
  /mail/text:
    post:
      tags:
        - postbox
      summary: 텍스트 편지 업로드
      consumes:
        - multipart/form-data
      security:
        - Authorization: []
      parameters:
        - name: member
          in: fromData
          type: array
          items:
            type: integer
          example: [3303580750, 3304133093]
        - name: text
          in: fromData
          type: string
          required: true
      responses:
        '200':
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              message:
                type: string
                example: 1ee0cbce41a4c539
        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
        '401':
          description: 토큰 오류
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 401
              isSuccess:  
                type: boolean
                example: false
              error:
                type: string
                example: 유효하지 않은 토큰입니다.
             
        '4001':
          description: 파라미터 오류
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 4001
              isSuccess:
                type: boolean
                example: false
              message:
                type: string
                example: 쿼리 실행 시 전달되는 파라미터가 잘못되었습니다. 파라미터 개수 혹은 파라미터 형식을 확인해주세요.
      